---
title: "Lab#7_Hw#7"
author: "Hassan Fayyaz"
date: "11/11/2021"
output: html_document
---

#################################################################
#1. What are the names of the people in your study group?
#'Hassan Fayyaz, Thakur Prasad Ghimire, Rimo Akther, Adelia Fida'
#################################################################

rm(list = ls(all = TRUE))
setwd("C:/Users/hassa/Desktop/Fall 2021/1_Econometrics_(B2000)/Homeworks/1_HW")
load("Household_Pulse_data.RData")

#################################################################
#Loading & Understanding Data
#################################################################


attach(Household_Pulse_data)
'The following objects are masked from Household_Pulse_data (pos = 5):

    ANXIOUS, ANYWORK, CHILDFOOD, CHLDCARE, CURFOODSUF, DOSESRV, eat_in_restaurant, EEDUC, EGENID_BIRTH, ENROLLNONE, EST_ST, EVICT, FORCLOSE, GENID_DESCRIBE, GETVACRV, HADCOVID,
    INCOME, KIDDOSES, KIDGETVAC, KIDS_12_17Y, KIDS_5_11Y, KIDS_LT5Y, KINDWORK, LIVQTRRV, MORTCUR, MS, Num_kids_homeschool, Num_kids_Priv_School, Num_kids_Pub_School, PRIVHLTH,
    PUBHLTH, RECVDVACC, REGION, RENTCUR, RHISPANIC, RRACE, RSNNOWRKRV, SEXUAL_ORIENTATION, Shop_in_store, TENURE, Works_onsite, works_remote, WORRY, WRKLOSSRV

The following objects are masked from Household_Pulse_data (pos = 6):

    ANXIOUS, ANYWORK, CHILDFOOD, CHLDCARE, CURFOODSUF, DOSESRV, eat_in_restaurant, EEDUC, EGENID_BIRTH, ENROLLNONE, EST_ST, EVICT, FORCLOSE, GENID_DESCRIBE, GETVACRV, HADCOVID,
    INCOME, KIDDOSES, KIDGETVAC, KIDS_12_17Y, KIDS_5_11Y, KIDS_LT5Y, KINDWORK, LIVQTRRV, MORTCUR, MS, Num_kids_homeschool, Num_kids_Priv_School, Num_kids_Pub_School, PRIVHLTH,
    PUBHLTH, RECVDVACC, REGION, RENTCUR, RHISPANIC, RRACE, RSNNOWRKRV, SEXUAL_ORIENTATION, Shop_in_store, TENURE, Works_onsite, works_remote, WORRY, WRKLOSSRV

The following objects are masked from Household_Pulse_data (pos = 10):

    ANXIOUS, ANYWORK, CHILDFOOD, CHLDCARE, CURFOODSUF, DOSESRV, eat_in_restaurant, EEDUC, EGENID_BIRTH, ENROLLNONE, EST_ST, EVICT, FORCLOSE, GENID_DESCRIBE, GETVACRV, HADCOVID,
    INCOME, KIDDOSES, KIDGETVAC, KIDS_12_17Y, KIDS_5_11Y, KIDS_LT5Y, KINDWORK, LIVQTRRV, MORTCUR, MS, Num_kids_homeschool, Num_kids_Priv_School, Num_kids_Pub_School, PRIVHLTH,
    PUBHLTH, RECVDVACC, REGION, RENTCUR, RHISPANIC, RRACE, RSNNOWRKRV, SEXUAL_ORIENTATION, Shop_in_store, TENURE, Works_onsite, works_remote, WORRY, WRKLOSSRV

The following objects are masked from Household_Pulse_data (pos = 11):

    ANXIOUS, ANYWORK, CHILDFOOD, CHLDCARE, CURFOODSUF, DOSESRV, eat_in_restaurant, EEDUC, EGENID_BIRTH, ENROLLNONE, EST_ST, EVICT, FORCLOSE, GENID_DESCRIBE, GETVACRV, HADCOVID,
    INCOME, KIDDOSES, KIDGETVAC, KIDS_12_17Y, KIDS_5_11Y, KIDS_LT5Y, KINDWORK, LIVQTRRV, MORTCUR, MS, Num_kids_homeschool, Num_kids_Priv_School, Num_kids_Pub_School, PRIVHLTH,
    PUBHLTH, RECVDVACC, REGION, RENTCUR, RHISPANIC, RRACE, RSNNOWRKRV, SEXUAL_ORIENTATION, Shop_in_store, TENURE, Works_onsite, works_remote, WORRY, WRKLOSSRV

The following objects are masked from Household_Pulse_data (pos = 13):

    ANXIOUS, ANYWORK, CHILDFOOD, CHLDCARE, CURFOODSUF, DOSESRV, eat_in_restaurant, EEDUC, EGENID_BIRTH, ENROLLNONE, EST_ST, EVICT, FORCLOSE, GENID_DESCRIBE, GETVACRV, HADCOVID,
    INCOME, KIDDOSES, KIDGETVAC, KIDS_12_17Y, KIDS_5_11Y, KIDS_LT5Y, KINDWORK, LIVQTRRV, MORTCUR, MS, Num_kids_homeschool, Num_kids_Priv_School, Num_kids_Pub_School, PRIVHLTH,
    PUBHLTH, RECVDVACC, REGION, RENTCUR, RHISPANIC, RRACE, RSNNOWRKRV, SEXUAL_ORIENTATION, Shop_in_store, TENURE, Works_onsite, works_remote, WORRY, WRKLOSSRV

The following objects are masked from Household_Pulse_data (pos = 14):

    ANXIOUS, ANYWORK, CHILDFOOD, CHLDCARE, CURFOODSUF, DOSESRV, eat_in_restaurant, EEDUC, EGENID_BIRTH, ENROLLNONE, EST_ST, EVICT, FORCLOSE, GENID_DESCRIBE, GETVACRV, HADCOVID,
    INCOME, KIDDOSES, KIDGETVAC, KIDS_12_17Y, KIDS_5_11Y, KIDS_LT5Y, KINDWORK, LIVQTRRV, MORTCUR, MS, Num_kids_homeschool, Num_kids_Priv_School, Num_kids_Pub_School, PRIVHLTH,
    PUBHLTH, RECVDVACC, REGION, RENTCUR, RHISPANIC, RRACE, RSNNOWRKRV, SEXUAL_ORIENTATION, Shop_in_store, TENURE, Works_onsite, works_remote, WORRY, WRKLOSSRV

The following objects are masked from Household_Pulse_data (pos = 15):

    ANXIOUS, ANYWORK, CHILDFOOD, CHLDCARE, CURFOODSUF, DOSESRV, eat_in_restaurant, EEDUC, EGENID_BIRTH, ENROLLNONE, EST_ST, EVICT, FORCLOSE, GENID_DESCRIBE, GETVACRV, HADCOVID,
    INCOME, KIDDOSES, KIDGETVAC, KIDS_12_17Y, KIDS_5_11Y, KIDS_LT5Y, KINDWORK, LIVQTRRV, MORTCUR, MS, Num_kids_homeschool, Num_kids_Priv_School, Num_kids_Pub_School, PRIVHLTH,
    PUBHLTH, RECVDVACC, REGION, RENTCUR, RHISPANIC, RRACE, RSNNOWRKRV, SEXUAL_ORIENTATION, Shop_in_store, TENURE, Works_onsite, works_remote, WORRY, WRKLOSSRV

The following objects are masked from Household_Pulse_data (pos = 16):

    ANXIOUS, ANYWORK, CHILDFOOD, CHLDCARE, CURFOODSUF, DOSESRV, eat_in_restaurant, EEDUC, EGENID_BIRTH, ENROLLNONE, EST_ST, EVICT, FORCLOSE, GENID_DESCRIBE, GETVACRV, HADCOVID,
    INCOME, KIDDOSES, KIDGETVAC, KIDS_12_17Y, KIDS_5_11Y, KIDS_LT5Y, KINDWORK, LIVQTRRV, MORTCUR, MS, Num_kids_homeschool, Num_kids_Priv_School, Num_kids_Pub_School, PRIVHLTH,
    PUBHLTH, RECVDVACC, REGION, RENTCUR, RHISPANIC, RRACE, RSNNOWRKRV, SEXUAL_ORIENTATION, Shop_in_store, TENURE, Works_onsite, works_remote, WORRY, WRKLOSSRV'
    
summary(Household_Pulse_data)
'RHISPANIC       RRACE                EEDUC               MS        EGENID_BIRTH       GENID_DESCRIBE       SEXUAL_ORIENTATION                      KIDS_LT5Y                         KIDS_5_11Y   
 Not Hispanic:62660   White:56938   less than hs:  411   NA       :  881   male  :27592   NA         : 1131   NA            : 1506    NA                        :62342   NA                       :58467  
 Hispanic    : 6454   Black: 5412   some hs     :  936   married  :40036   female:41522   male       :26796   gay or lesbian: 2343    Yes children under 5 in HH: 6772   Yes children 5 - 11 in HH:10647  
                      Asian: 3561   HS diploma  : 7857   widowed  : 3872                  female     :40263   straight      :61238                                                                        
                      Other: 3203   some coll   :14596   divorced :10310                  transgender:  202   bisexual      : 2288                                                                        
                                    assoc deg   : 7508   separated: 1214                  other      :  722   something else:  871                                                                        
                                    bach deg    :20075   never    :12801                                      dont know     :  868                                                                        
                                    adv deg     :17731                                                                                                                                                    
                     KIDS_12_17Y                                 ENROLLNONE                  RECVDVACC                          DOSESRV                          GETVACRV    
 NA                        :58046   NA                                :64285   NA                 :  851   NA                       : 9105   NA                      :61159  
 Yes children 12 - 17 in HH:11068   children not in any type of school: 4829   yes got vaxx       :60326   yes got all doses        :57762   definitely will get vaxx:  609  
                                                                               no did not get vaxx: 7937   yes plan to get all doses: 1993   probably will get vaxx  :  731  
                                                                                                           no will not get all doses:  254   unsure about vaxx       : 1584  
                                                                                                                                             probably not            : 1599  
                                                                                                                                             definitely not          : 3432  
                                                                                                                                                                             
                               KIDDOSES                        KIDGETVAC                          HADCOVID                      WRKLOSSRV                              ANYWORK     
 NA                                :58318   NA                      :65384   NA                       : 1363   NA                    : 1961   NA                           : 2135  
 Yes kids got or will get all doses: 7135   definitely will get vaxx:  487   yes doctor told had covid: 9122   yes recent HH job loss: 8058   yes employment in last 7 days:39237  
 no kids did not or will not       : 3661   probably will get vaxx  :  439   no did not               :58221   no recent HH job loss :59095   no employment in last 7 days :27742  
                                            unsure about vaxx       :  736   not sure                 :  408                                                                       
                                            probably not            :  593                                                                                                         
                                            definitely not          : 1036                                                                                                         
                                            dont know yet           :  439                                                                                                         
                KINDWORK                RSNNOWRKRV                                         CHLDCARE                              CURFOODSUF                                                  CHILDFOOD    
 NA                 :30540   NA              :42659   NA                                       :58419   NA                            : 6770   NA                                                 :64258  
 work for govt      : 6378   retired         :15024   yes impacts to childcare because pandemic: 2566   had enough food               :49234   often kids not eating enough because couldnt afford:  271  
 work for private co:21370   other           : 4027   no                                       : 8129   had enough but not what wanted: 9947   sometimes kids not eating enough                   : 1191  
 work for nonprofit : 5055   sick or disabled: 1451                                                     sometimes not enough food     : 2486   kids got enough food                               : 3394  
 self employed      : 4966   caring for kids : 1329                                                     often not enough food         :  677                                                              
 work in family biz :  805   laid off        : 1164                                                                                                                                                       
                             (Other)         : 3460                                                                                                                                                       
                                            ANXIOUS                                                  WORRY                                 TENURE                                     LIVQTRRV    
 NA                                             : 7946   NA                                             : 8016   NA                           :11103   live in detached 1 family          :41348  
 no anxiety over past 2 wks                     :26611   no worry over past 2 wks                       :31876   housing owned free and clear :16738   NA                                 :11336  
 several days anxiety over past 2 wks           :19794   several days worried over past 2 wks           :17936   housing owned with mortgage  :28016   live in bldg w 5+ apts             : 6731  
 more than half the days anxiety over past 2 wks: 6140   more than half the days worried over past 2 wks: 4979   housing rented               :12579   live in 1 family attached to others: 4628  
 nearly every day anxiety                       : 8623   nearly every day worry                         : 6307   housing occupied without rent:  678   live in mobile home                : 1781  
                                                                                                                                                       live in building with 3-4 apts     : 1737  
                                                                                                                                                       (Other)                            : 1553  
            RENTCUR                     MORTCUR                                             EVICT                                                FORCLOSE               EST_ST     
 NA             :56572   NA                 :41200   NA                                        :67859   NA                                           :67695   California   : 5359  
 current on rent:11239   current on mortgage:26462   very likely evicted in next 2 months      :  207   very likely forclosed in next 2 months       :   65   Texas        : 3766  
 behind on rent : 1303   behind on mortgage : 1452   somewhat likely evicted in next 2 months  :  377   somewhat likely forclosed in next 2 months   :  218   Florida      : 2728  
                                                     not very likely evicted in next 2 months  :  345   not very likely forclosed in next 2 months   :  474   Washington   : 2634  
                                                     not at all likely evicted in next 2 months:  326   not at all forclosed evicted in next 2 months:  662   Massachusetts: 1965  
                                                                                                                                                              Oregon       : 1934  
                                                                                                                                                              (Other)      :50728  
                   PRIVHLTH                      PUBHLTH            REGION                          INCOME      Num_kids_Pub_School Num_kids_Priv_School Num_kids_homeschool        Works_onsite  
 has private health ins:46869   has public health ins:23346   Northeast:10478   NA                     :20335   Min.   :0.00        Min.   :0.00         Min.   :0.00        NA           : 6350  
 no private health ins :11275   no public health ins :33381   South    :22680   HH income $75 - 99.9   :10117   1st Qu.:1.00        1st Qu.:0.00         1st Qu.:0.00        worked onsite:34918  
 NA                    :10970   NA                   :12387   Midwest  :13651   HH income $35k - 49.9  : 9330   Median :2.00        Median :1.00         Median :1.00        no           :27846  
                                                              West     :22305   HH income $50k - 74.9  : 7830   Mean   :1.71        Mean   :1.03         Mean   :0.87                             
                                                                                HH income $150 - 199   : 6117   3rd Qu.:2.00        3rd Qu.:2.00         3rd Qu.:2.00                             
                                                                                HH income $25k - $34.9k: 5805   Max.   :4.00        Max.   :2.00         Max.   :2.00                             
                                                                                (Other)                : 9580   NA's   :55108       NA's   :66430        NA's   :67421                            
          works_remote            Shop_in_store                   eat_in_restaurant
 NA             : 8022   NA              : 6873   NA                       : 7217  
 worked remotely:22863   shopped in store:53576   eat at restaurant indoors:32405  
 no             :38229   no              : 8665   no                       :29492
'



names(Household_Pulse_data)
'[1] "RHISPANIC"            "RRACE"                "EEDUC"                "MS"                   "EGENID_BIRTH"         "GENID_DESCRIBE"       "SEXUAL_ORIENTATION"   "KIDS_LT5Y"           
 [9] "KIDS_5_11Y"           "KIDS_12_17Y"          "ENROLLNONE"           "RECVDVACC"            "DOSESRV"              "GETVACRV"             "KIDDOSES"             "KIDGETVAC"           
[17] "HADCOVID"             "WRKLOSSRV"            "ANYWORK"              "KINDWORK"             "RSNNOWRKRV"           "CHLDCARE"             "CURFOODSUF"           "CHILDFOOD"           
[25] "ANXIOUS"              "WORRY"                "TENURE"               "LIVQTRRV"             "RENTCUR"              "MORTCUR"              "EVICT"                "FORCLOSE"            
[33] "EST_ST"               "PRIVHLTH"             "PUBHLTH"              "REGION"               "INCOME"               "Num_kids_Pub_School"  "Num_kids_Priv_School" "Num_kids_homeschool" 
[41] "Works_onsite"         "works_remote"         "Shop_in_store"        "eat_in_restaurant"   
> '

####################################################################################################################
#2. Write up the results of your work in Lab 7. Explain each step and your choices. 
#Don't just upload a mass of output, make it clear and understandable about what's going on in the data. Impress me.
#####################################################################################################################

#First lets count the missing values in the Get vaccine variable
sum(is.na(Household_Pulse_data$RECVDVACC))
'[1] 0
> '

##Then lets replace NA strings with NULL according to R
library(dplyr)

#count missing values in the RECVDVACC variable
sum(is.na(Household_Pulse_data$RECVDVACC))
'[1] 0'

##Create the dependent variable vaxx
Household_Pulse_data$vaxx <-(Household_Pulse_data$RECVDVACC == "yes got vaxx")
Household_Pulse_data$vaxx =  as.factor(Household_Pulse_data$vaxx)
table(Household_Pulse_data$vaxx)

'FALSE  TRUE 
 8788 60326 
> '

dim(Household_Pulse_data) #data dimension

';[1] 69114    45
> '

df_household = Household_Pulse_data[Household_Pulse_data$KIDS_12_17Y!="NA",]
dim(df_household) #data dimension

'[1] 11068    45
> '

#Then find some basic statistics – what fraction are not vaxxed?

a=table(df_household$vaxx)
barplot(a,main="Vaxx Comparison Using BarPlot",
        ylab="Count",
        xlab="Vaxx",
        col=rainbow(16),
        legend=rownames(a))

pct=round(a/sum(a)*100)

lbs=paste(c("FALSE","TRUE")," ",pct,"%",sep=" ")

install.packages("plotrix")

'WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/hassa/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/plotrix_3.8-2.zip'
Content type 'application/zip' length 1139092 bytes (1.1 MB)
downloaded 1.1 MB

package ‘plotrix’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\hassa\AppData\Local\Temp\RtmpUl0HPU\downloaded_packages'

library(plotrix)

pie3D(a,labels=lbs, main="Pie Chart Showing  Non-vaxxed and vaxxed ")

#(Later go back to look at simple stats for subgroups to see if there are sharp differences.) other subgroups are: KIDS_12_17Y - select 12-17Y subgroup

df_KidsLT5Y = Household_Pulse_data[Household_Pulse_data$KIDS_LT5Y!="NA",]

#plot pie chart 
b=table(df_KidsLT5Y$vaxx)

pct2=round(b/sum(b)*100)

lbs=paste(c("FALSE","TRUE")," ",pct,"%",sep=" ")

library(plotrix)

pie3D(b,labels=lbs, main="Pie Chart Showing  Non-vaxxed and vaxxed ")

#other subgroups are: KIDS_5_11Y - select 5-11Y subgroup

df_Kids5_11Y = Household_Pulse_data[Household_Pulse_data$KIDS_5_11Y!="NA",]
#plot pie chart 
c=table(df_Kids5_11Y$vaxx)
pct3=round(c/sum(c)*100)
lbs=paste(c("FALSE","TRUE")," ",pct,"%",sep=" ")
library(plotrix)
pie3D(b,labels=lbs,
      main="Pie Chart Showing  Non-vaxxed and vaxxed ")

#NO, there were no sharp differences
#Run several different types of models to explain vaccination rates with some explanatory variables, vaxx ~ TBIRTH_YEAR + EEDUC + MS + RRACE + RHISPANIC + GENID_DESCRIBE + REGION.

df_household = subset(df_household,select = c(vaxx,EEDUC,MS,RRACE,RHISPANIC,GENID_DESCRIBE,REGION))
               
head(df_household)
'vaxx      EEDUC      MS RRACE    RHISPANIC GENID_DESCRIBE REGION
5  TRUE  some coll   never Black Not Hispanic         female  South
10 TRUE    adv deg married White Not Hispanic         female  South
18 TRUE  assoc deg married White Not Hispanic           male   West
24 TRUE HS diploma   never Other Not Hispanic         female   West
33 TRUE   bach deg married Black Not Hispanic           male  South
48 TRUE  assoc deg married Asian Not Hispanic         female   West
> '

str(df_household)
''data.frame':	11068 obs. of  7 variables:
 $ vaxx          : Factor w/ 2 levels "FALSE","TRUE": 2 2 2 2 2 2 2 2 2 1 ...
 $ EEDUC         : Factor w/ 7 levels "less than hs",..: 4 7 5 3 6 5 6 7 6 4 ...
 $ MS            : Factor w/ 6 levels "NA","married",..: 6 2 2 6 2 2 2 2 2 4 ...
 $ RRACE         : Factor w/ 4 levels "White","Black",..: 2 1 1 4 2 3 3 4 4 1 ...
 $ RHISPANIC     : Factor w/ 2 levels "Not Hispanic",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ GENID_DESCRIBE: Factor w/ 5 levels "NA","male","female",..: 3 3 2 3 2 3 2 3 3 2 ...
 $ REGION        : Factor w/ 4 levels "Northeast","South",..: 2 2 4 4 2 4 1 2 4 4 ...
>'

install.packages("dummies")
'WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/hassa/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/dummies_1.5.6.zip'
Content type 'application/zip' length 30087 bytes (29 KB)
downloaded 29 KB

package ‘dummies’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\hassa\AppData\Local\Temp\RtmpUl0HPU\downloaded_packages'

library(dummies)
'dummies-1.5.6 provided by Decision Patterns'

## dummies-1.5.6 provided by Decision Patterns
vars=c("EEDUC","MS" ,"RRACE","RHISPANIC","GENID_DESCRIBE","REGION")
df_household[,vars] <- lapply(df_household[,vars] , factor)
df_new<-dummy.data.frame(df_household,names = vars,sep=".")

'Warning messages:
1: In model.matrix.default(~x - 1, model.frame(~x - 1), contrasts = FALSE) :
  non-list contrasts argument ignored
2: In model.matrix.default(~x - 1, model.frame(~x - 1), contrasts = FALSE) :
  non-list contrasts argument ignored
3: In model.matrix.default(~x - 1, model.frame(~x - 1), contrasts = FALSE) :
  non-list contrasts argument ignored
4: In model.matrix.default(~x - 1, model.frame(~x - 1), contrasts = FALSE) :
  non-list contrasts argument ignored
5: In model.matrix.default(~x - 1, model.frame(~x - 1), contrasts = FALSE) :
  non-list contrasts argument ignored
6: In model.matrix.default(~x - 1, model.frame(~x - 1), contrasts = FALSE) :
  non-list contrasts argument ignored'


#split the data into train and test data 80% of the sample size

set.seed(654321)

smp_size <- floor(0.80 * nrow(df_new))
train_ind <- sample(seq_len(nrow(df_new)), size = smp_size)
train.set <- df_new[train_ind, ]
test.set <- df_new[-train_ind, ]

dim(train.set)
#[1] 8854   29

str(train.set)
''data.frame':	8854 obs. of  29 variables:
 $ vaxx                      : Factor w/ 2 levels "FALSE","TRUE": 2 2 2 2 2 2 2 2 2 2 ...
 $ EEDUC.less than hs        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ EEDUC.some hs             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ EEDUC.HS diploma          : int  0 0 1 0 0 0 0 0 0 0 ...
 $ EEDUC.some coll           : int  0 0 0 0 0 0 0 0 0 0 ...
 $ EEDUC.assoc deg           : int  1 0 0 1 0 0 0 0 0 1 ...
 $ EEDUC.bach deg            : int  0 1 0 0 0 0 0 1 0 0 ...
 $ EEDUC.adv deg             : int  0 0 0 0 1 1 1 0 1 0 ...
 $ MS.NA                     : int  0 0 0 0 0 0 0 0 0 0 ...
 $ MS.married                : int  1 1 0 0 1 1 1 1 1 0 ...
 $ MS.widowed                : int  0 0 0 0 0 0 0 0 0 1 ...
 $ MS.divorced               : int  0 0 0 1 0 0 0 0 0 0 ...
 $ MS.separated              : int  0 0 0 0 0 0 0 0 0 0 ...
 $ MS.never                  : int  0 0 1 0 0 0 0 0 0 0 ...
 $ RRACE.White               : int  1 1 0 1 1 1 1 1 0 1 ...
 $ RRACE.Black               : int  0 0 0 0 0 0 0 0 0 0 ...
 $ RRACE.Asian               : int  0 0 1 0 0 0 0 0 1 0 ...
 $ RRACE.Other               : int  0 0 0 0 0 0 0 0 0 0 ...
 $ RHISPANIC.Not Hispanic    : int  1 1 0 1 1 1 1 1 1 1 ...
 $ RHISPANIC.Hispanic        : int  0 0 1 0 0 0 0 0 0 0 ...
 $ GENID_DESCRIBE.NA         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ GENID_DESCRIBE.male       : int  0 0 0 0 0 1 0 1 1 1 ...
 $ GENID_DESCRIBE.female     : int  1 1 1 1 1 0 1 0 0 0 ...
 $ GENID_DESCRIBE.transgender: int  0 0 0 0 0 0 0 0 0 0 ...
 $ GENID_DESCRIBE.other      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ REGION.Northeast          : int  0 1 0 0 1 0 0 0 1 0 ...
 $ REGION.South              : int  0 0 0 1 0 1 0 0 0 1 ...
 $ REGION.Midwest            : int  0 0 0 0 0 0 1 0 0 0 ...
 $ REGION.West               : int  1 0 1 0 0 0 0 1 0 0 ...
 - attr(*, "dummies")=List of 6
  ..$ EEDUC         : int [1:7] 2 3 4 5 6 7 8
  ..$ MS            : int [1:6] 9 10 11 12 13 14
  ..$ RRACE         : int [1:4] 15 16 17 18
  ..$ RHISPANIC     : int [1:2] 19 20
  ..$ GENID_DESCRIBE: int [1:5] 21 22 23 24 25
  ..$ REGION        : int [1:4] 26 27 28 29
> '

#Logistic Regression Model
#We are using a logit regression in this case, such a regression gives us two outcomes all the time because the Y values in the graph are categorical and depend on the X variable

model_logit1 <- glm(vaxx~., family = binomial, data = train.set)
summary(model_logit1)

'Call:
glm(formula = vaxx ~ ., family = binomial, data = train.set)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.8428   0.3347   0.5238   0.7228   1.6370  

Coefficients: (6 not defined because of singularities)
                           Estimate Std. Error z value Pr(>|z|)    
(Intercept)                 1.26958    0.25673   4.945 7.61e-07 ***
`EEDUC.less than hs`       -1.75929    0.23014  -7.644 2.10e-14 ***
`EEDUC.some hs`            -1.83126    0.17751 -10.317  < 2e-16 ***
`EEDUC.HS diploma`         -1.70085    0.10440 -16.292  < 2e-16 ***
`EEDUC.some coll`          -1.39469    0.09709 -14.364  < 2e-16 ***
`EEDUC.assoc deg`          -1.10115    0.11027  -9.986  < 2e-16 ***
`EEDUC.bach deg`           -0.60445    0.09951  -6.075 1.24e-09 ***
`EEDUC.adv deg`                  NA         NA      NA       NA    
MS.NA                      -0.15839    0.32908  -0.481 0.630298    
MS.married                  0.47453    0.08076   5.876 4.21e-09 ***
MS.widowed                  0.61208    0.19063   3.211 0.001323 ** 
MS.divorced                 0.30281    0.10065   3.008 0.002625 ** 
MS.separated                0.07663    0.16292   0.470 0.638093    
MS.never                         NA         NA      NA       NA    
RRACE.White                 0.32693    0.10233   3.195 0.001400 ** 
RRACE.Black                 0.44048    0.13005   3.387 0.000707 ***
RRACE.Asian                 1.82863    0.22983   7.956 1.77e-15 ***
RRACE.Other                      NA         NA      NA       NA    
`RHISPANIC.Not Hispanic`   -0.37138    0.08460  -4.390 1.13e-05 ***
RHISPANIC.Hispanic               NA         NA      NA       NA    
GENID_DESCRIBE.NA          -0.15229    0.37457  -0.407 0.684322    
GENID_DESCRIBE.male         0.82176    0.22071   3.723 0.000197 ***
GENID_DESCRIBE.female       0.76170    0.21752   3.502 0.000462 ***
GENID_DESCRIBE.transgender  0.49643    0.48443   1.025 0.305479    
GENID_DESCRIBE.other             NA         NA      NA       NA    
REGION.Northeast            0.33236    0.09976   3.332 0.000863 ***
REGION.South               -0.23351    0.06981  -3.345 0.000823 ***
REGION.Midwest             -0.12765    0.07951  -1.606 0.108367    
REGION.West                      NA         NA      NA       NA    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 8817.1  on 8853  degrees of freedom
Residual deviance: 8055.5  on 8831  degrees of freedom
AIC: 8101.5

Number of Fisher Scoring iterations: 5

'

#Confusion matrix

library(caret)

'Loading required package: ggplot2
Loading required package: lattice'

pred_vals <- predict(model_logit1, test.set[,-1], type = "response")

'Warning message:
In predict.lm(object, newdata, se.fit, scale = 1, type = if (type ==  :
  prediction from a rank-deficient fit may be misleading'

pred_model_logit1 <- as.factor(pred_vals > 0.5)
table(pred = pred_model_logit1, true = test.set$vaxx)

'true
pred    FALSE TRUE
  FALSE     5    9
  TRUE    427 1773
> '

confusionMatrix(pred_model_logit1,test.set$vaxx,positive = "TRUE")

'Confusion Matrix and Statistics

          Reference
Prediction FALSE TRUE
     FALSE     5    9
     TRUE    427 1773
                                          
               Accuracy : 0.8031          
                 95% CI : (0.7859, 0.8195)
    No Information Rate : 0.8049          
    P-Value [Acc > NIR] : 0.5973          
                                          
                  Kappa : 0.0103          
                                          
 Mcnemar's Test P-Value : <2e-16          
                                          
            Sensitivity : 0.99495         
            Specificity : 0.01157         
         Pos Pred Value : 0.80591         
         Neg Pred Value : 0.35714         
             Prevalence : 0.80488         
         Detection Rate : 0.80081         
   Detection Prevalence : 0.99368         
      Balanced Accuracy : 0.50326         
                                          
       'Positive' Class : TRUE'

#Linear model; OLS model (convert vaxx into numeric)

train.set$vaxx = ifelse(train.set$vaxx =="TRUE",1,0)
test.set$vaxx = ifelse(test.set =="TRUE",1,0)
model_lpm1 <- lm(vaxx~., data = train.set)
summary(model_lpm1)

'Call:
lm(formula = vaxx ~ ., data = train.set)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.05040  0.03022  0.13333  0.23812  0.63151 

Coefficients: (6 not defined because of singularities)
                           Estimate Std. Error t value Pr(>|t|)    
(Intercept)                 0.71049    0.04158  17.089  < 2e-16 ***
`EEDUC.less than hs`       -0.24941    0.03861  -6.459 1.11e-10 ***
`EEDUC.some hs`            -0.27270    0.02966  -9.195  < 2e-16 ***
`EEDUC.HS diploma`         -0.24486    0.01457 -16.810  < 2e-16 ***
`EEDUC.some coll`          -0.18011    0.01246 -14.450  < 2e-16 ***
`EEDUC.assoc deg`          -0.12640    0.01452  -8.706  < 2e-16 ***
`EEDUC.bach deg`           -0.05494    0.01137  -4.833 1.37e-06 ***
`EEDUC.adv deg`                  NA         NA      NA       NA    
MS.NA                      -0.03729    0.05884  -0.634 0.526249    
MS.married                  0.08509    0.01344   6.331 2.55e-10 ***
MS.widowed                  0.10590    0.02836   3.734 0.000190 ***
MS.divorced                 0.05952    0.01640   3.630 0.000286 ***
MS.separated                0.01483    0.02757   0.538 0.590755    
MS.never                         NA         NA      NA       NA    
RRACE.White                 0.05614    0.01667   3.367 0.000763 ***
RRACE.Black                 0.07287    0.02082   3.499 0.000468 ***
RRACE.Asian                 0.17753    0.02309   7.688 1.66e-14 ***
RRACE.Other                      NA         NA      NA       NA    
`RHISPANIC.Not Hispanic`   -0.06072    0.01239  -4.901 9.69e-07 ***
RHISPANIC.Hispanic               NA         NA      NA       NA    
GENID_DESCRIBE.NA          -0.02204    0.06412  -0.344 0.731097    
GENID_DESCRIBE.male         0.13801    0.03692   3.738 0.000186 ***
GENID_DESCRIBE.female       0.13062    0.03656   3.573 0.000355 ***
GENID_DESCRIBE.transgender  0.07777    0.07980   0.975 0.329815    
GENID_DESCRIBE.other             NA         NA      NA       NA    
REGION.Northeast            0.04077    0.01318   3.093 0.001991 ** 
REGION.South               -0.03642    0.01027  -3.548 0.000391 ***
REGION.Midwest             -0.01984    0.01168  -1.698 0.089565 .  
REGION.West                      NA         NA      NA       NA    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.3825 on 8831 degrees of freedom
Multiple R-squared:  0.08175,	Adjusted R-squared:  0.07947 
F-statistic: 35.74 on 22 and 8831 DF,  p-value: < 2.2e-16'

###################################################################################################################################################################
#3. Each person in the group should find 2 more academic articles related to your current choice of final project. 
#Write a short paragraph on each, concentrating on what data is used (and whether it is accessible), what econometric techniques, and what questions are addressed.
####################################################################################################################################################################

#Question#3 is answered separately as a pdf


